backend:
  name: github
  repo: miyazakimaiko/portfolio-blog-2021
  branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: updatedAt, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: topics, label: Topics, widget: list }
      - { name: featuredImage, label: Featured Image, widget: image }
      - { name: featured, label: Featured, widget: boolean }
      - { name: seoTitle, label: SEO Title }
      - { name: seoDescription, label: SEO Description }
      - { name: seoImage, label: SEO Image }
      - { name: seoAuthor, label: SEO Author }
      - { name: relatedFilePaths, label: Related File Paths widget: list }

  - name: topics
    label: Topics
    folder: content/topics
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
  